# -*- coding: utf-8 -*-
"""Te damos la bienvenida a Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

trabajadores = ["Juan Pérez", "María García", "Carlos López", "Ana Martínez", "Pedro Rodríguez", "Laura Hernández", "Miguel Sánchez", "Isabel Gómez", "Francisco Díaz", "Elena Fernández"]
sueldos = []

import random

def asignar_sueldo_aleatorio(trabajadores):
    sueldos.clear()  # Limpiar lista de sueldos
    for trabajador in trabajadores:
        aleatorio = random.randint(300000, 2500000)
        print(trabajador, aleatorio)
        sueldos.append(aleatorio)

def clasificar_sueldo(sueldos):
    for sueldo in sueldos:
        if sueldo <= 800000:
            print("Sueldo menor a $800.000:", sueldo)
        elif sueldo >= 800000 and sueldo <= 2000000:
            print("Sueldo entre $800.000 y $2.000.000:", sueldo)
        elif sueldo >= 2000000:
            print("Sueldo superior a $2.000.000:", sueldo)

def ver_estadisticas(sueldos):
    sueldo_mayor = max(sueldos)
    print("El sueldo más alto es:", sueldo_mayor)

    sueldo_menor = min(sueldos)
    print("El sueldo más bajo es:", sueldo_menor)

    promedio_sueldo = sum(sueldos) / len(sueldos)
    print("El sueldo promedio es:", promedio_sueldo)

    from scipy.stats import gmean #"scipy.stats" no me funciono en visual studio pero si en el colab
    media_geometrica = gmean(sueldos)
    print("La media geométrica es:", media_geometrica)

def reporte_sueldo(trabajadores, sueldos):
    print("Nombre: \t\t\tSueldo Bruto:\t\tDescuento Salud: \t\tDescuento AFP: \t\t\tSueldo Líquido:\n")
    for i in range(len(trabajadores)):
        descuento_salud = sueldos[i] * 0.07
        descuento_afp = sueldos[i] * 0.12
        sueldo_liquido = sueldos[i] - descuento_salud - descuento_afp
        print(f"{trabajadores[i]}\t\t\t{sueldos[i]}\t\t{descuento_salud}\t\t\t{descuento_afp} \t\t\t{sueldo_liquido}\n")


with open("trabajadores.txt", mode="w", newline="") as trabajadores_csv:
    for trabajador in trabajadores:
        trabajadores_csv.write(trabajador + "\n")

def leer():
    with open("trabajadores.txt", mode="r", newline="") as trabajadores_csv:
        contenido = trabajadores_csv.read()
        print(contenido)

#Menu
while True:
    print("1.- Asignar sueldo aleatorio")
    print("2.- Clasificar sueldo")
    print("3.- Ver estadísticas")
    print("4.- Reporte de sueldo")
    print("5.- Salir del programa")

    opcion = input("Ingrese una opción: ")

    if opcion == "1":
        asignar_sueldo_aleatorio(trabajadores)

    elif opcion == "2":
        clasificar_sueldo(sueldos)
        print("Clasificación exitosa")

    elif opcion == "3":
        print("Estadísticas")
        ver_estadisticas(sueldos)

    elif opcion == "4":
        print("Reporte de sueldo")
        reporte_sueldo(trabajadores, sueldos)

    elif opcion == "5":
        print("Salir del programa")
        break

    else:
        print("Opción inválida. Intente nuevamente.")